select * from customer;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT `gender`, SUM(`purchase_amount_(usd)`) AS total_revenue
FROM customer
GROUP BY `gender`;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT * FROM customer
WHERE `discount_applied` = 'Yes' 
AND `purchase_amount_(usd)` > (SELECT AVG(`purchase_amount_(usd)`) 
FROM customer);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT `item_purchased`, AVG(`review_rating`) AS avg_rating
FROM customer
GROUP BY `item_purchased`
ORDER BY avg_rating DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT `shipping_type`, ROUND(AVG(`purchase_amount_(usd)`),2) AS avg_purchase
FROM customer
where shipping_type in ('standard','express')
GROUP BY `shipping_type`;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between 
-- subscribers and non-subscribers.
SELECT `subscription_status`, 
AVG(`purchase_amount_(usd)`) AS avg_spend,
SUM(`purchase_amount_(usd)`) AS total_revenue
FROM customer
GROUP BY `subscription_status`;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT `item_purchased`,
SUM(CASE WHEN `discount_applied` = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS discount_percentage
FROM customer
GROUP BY `item_purchased`
ORDER BY discount_percentage DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of 
-- previous purchases, and show the count of each segment.
SELECT 
CASE 
 WHEN `previous_purchases` <= 1 THEN 'New'
 WHEN `previous_purchases` BETWEEN 2 AND 5 THEN 'Returning'
 ELSE 'Loyal'
END AS customer_segment,
COUNT(*) AS count
FROM customer
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
WITH ranked_products AS (
  SELECT `category`, `item_purchased`, COUNT(*) AS cnt,
  ROW_NUMBER() OVER (PARTITION BY `category` ORDER BY COUNT(*) DESC) AS rn
  FROM customer GROUP BY `category`, `item_purchased`
)
SELECT * FROM ranked_products WHERE rn <= 3;



-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also 
-- likely to subscribe?
SELECT subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;


-- Q10. What is the revenue contribution of each age group?
SELECT 
CASE 
 WHEN `age` BETWEEN 18 AND 25 THEN 'Young Adult'
 WHEN `age` BETWEEN 26 AND 35 THEN 'Adult'
 WHEN `age` BETWEEN 36 AND 50 THEN 'Middle-aged'
 ELSE 'Senior'
END AS age_group,
SUM(`purchase_amount_(usd)`) AS total_revenue
FROM customer
GROUP BY 
CASE 
 WHEN `age` BETWEEN 18 AND 25 THEN 'Young Adult'
 WHEN `age` BETWEEN 26 AND 35 THEN 'Adult'
 WHEN `age` BETWEEN 36 AND 50 THEN 'Middle-aged'
 ELSE 'Senior'
END
ORDER BY total_revenue DESC;


